title: Iyinoluwa Ayodele CEAMLS SAIRI Website Summer 2024 
logo: "C:\Users\grace\Downloads\Iyinoluwa Ayodele headshot.jpg"
description: Hi! My name is Iyinoluwa Ayodele and this is my CEAMLS SAIRI Website for Summer 2024.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
